### PR TITLE
Maintenance: Updates deps, CI steps and cleaner logs

### PR DESCRIPTION
**Pull request by phated**
In relation to #54, I'm trying to update things where possible. Would love your feedback @bryphe and @ManasJayanth!

### CODE REVIEW

**Comment by phated** [comment]
I'm trying to figure out why the `--env` test is failing

**Comment by phated** [comment]
Ah, finally figured it out. It's that the `mount` command now prints the values to stdout when you run the command.

**Comment by phated** [comment]
I reverted the esy lockfile and dependency changes because newer deps caused a problem that I couldn't solve, but I kept all the process improvements in place.

If these changes are merged and released, I believe it will pick up the newest cygwin stuff that will also solve #54

**Comment by phated** [comment]
I've also tested a fresh git-pull and ran all the scripts and everything works in my Windows 10 VM

**Review by ManasJayanth — APPROVED** [review]
Summary: 
* Adds `npm run test-exe` to test native `esy-bash` binary while development.
* Update a few NPM deps
* Redirects mounting logs to /dev/null

**Pull request merged**
